spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: quest
    password: {cipher}
    53f6184fd8a68315b213c751d45453322f18efa45309481808690665ee7aff98f89f67a027cde6e708294728a24848d5
  zipkin:
    base-url: http://localhost:9411/
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: {cipher}
    6e2355f04f1767a378273ae156ced7a34188abf7ac0faf30d9b543a890300d92b82786a6aee394f949d42c2cfcc8c6ea
    url: jdbc:postgresql://localhost:5433/employee_db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

logging:
  level:
    org:
      springframework:
        web: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

feign:
  circuitbreaker:
    enabled: true
    alphanumeric-ids:
      enabled: true


resilience4j:
  circuitbreaker:
    instances:
      DEPARTMENT-SERVICE:
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimumNumberOfCalls: 5
        failureHealthIndicator: 50
        registerHealthIndicator: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      ORGANIZATION-SERVICE:
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimumNumberOfCalls: 5
        failureHealthIndicator: 50
        registerHealthIndicator: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      ORGANIZATION-SERVICE:
        registerHealthIndicator: true
        waitDuration: 1s
        maxRetryAttempts: 5
      DEPARTMENT-SERVICE:
        registerHealthIndicator: true
        waitDuration: 1s
        maxRetryAttempts: 5
        
management:
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path : /api/employees/gui-docs
  api-docs:
    path : /api/employees/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
