spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: quest
    password: '{cipher}856bda550970bce018f45d73815654692ca4fd9f484dfafbdbdd55b9139b7cfa41fd6287b303eb379de1b077b680ce2e'
  zipkin:
    base-url: http://localhost:9411/
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: '{cipher}d24e2b053b53672cf3c9e38238f8f6dadd32068bc252b5cd70c6972c6a5bb4f829552bc068cb22fbbb6b228ced4213e3'
    url: jdbc:postgresql://localhost:5433/employee_db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

logging:
  level:
    org:
      springframework:
        web: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

feign:
  circuitbreaker:
    enabled: true
    alphanumeric-ids:
      enabled: true


resilience4j:
  circuitbreaker:
    instances:
      DEPARTMENT-SERVICE:
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimumNumberOfCalls: 5
        failureHealthIndicator: 50
        registerHealthIndicator: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      ORGANIZATION-SERVICE:
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimumNumberOfCalls: 5
        failureHealthIndicator: 50
        registerHealthIndicator: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      ORGANIZATION-SERVICE:
        registerHealthIndicator: true
        waitDuration: 1s
        maxRetryAttempts: 5
      DEPARTMENT-SERVICE:
        registerHealthIndicator: true
        waitDuration: 1s
        maxRetryAttempts: 5
        
management:
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path : /api/employees/gui-docs
  api-docs:
    path : /api/employees/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
