spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    password: quest
    username: quest
  zipkin:
    base-url: http://zipkin:9411/
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: secret_postgres_password
    url: jdbc:postgresql://employee-db:5432/employee_db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

feign:
  circuitbreaker:
    enabled: true
    alphanumeric-ids:
      enabled: true


resilience4j:
  circuitbreaker:
    instances:
      DEPARTMENT-SERVICE:
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimumNumberOfCalls: 5
        failureHealthIndicator: 50
        registerHealthIndicator: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      ORGANIZATION-SERVICE:
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimumNumberOfCalls: 5
        failureHealthIndicator: 50
        registerHealthIndicator: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      ORGANIZATION-SERVICE:
        registerHealthIndicator: true
        waitDuration: 1s
        maxRetryAttempts: 5
      DEPARTMENT-SERVICE:
        registerHealthIndicator: true
        waitDuration: 1s
        maxRetryAttempts: 5
        
management:
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path : /api/employees/gui-docs
  api-docs:
    path : /api/employees/api-docs

eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
      "prometheus.port": "8080"
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
