spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: quest
    password: '{cipher}f2d1d42658d7f7b7b80179cc6d9337e6b7aa4342f4d3fdbb3aa45e7715cff5b6'
  zipkin:
    base-url: http://zipkin:9411/
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: '{cipher}85cf44a3a4924460c3b65d8d965c215bd3eba664a68b00862589a236601919a110894531dd54ecb6bb9a0c7768cb1dc6'
    url: jdbc:postgresql://organization-db:5432/organization_db
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path : /api/organizations/gui-docs
  api-docs:
    path : /api/organizations/api-docs

eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
      "prometheus.port": "8080"
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

logging:
  level:
    org:
      springframework:
        web: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
