spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: quest
    password: '{cipher}025fa1585a687fd5c44d469f72f38acb100a6a4c0ce841b5720f5780a654b533'
  zipkin:
    base-url: http://zipkin:9411/
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: '{cipher}48061eef0a7c6361ad0a739586e7936dee0ad59c7161af6bd991549715f2b5a393afc9318b24a93fc9e2575388f787d6'
    url: jdbc:postgresql://organization-db:5432/organization_db
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path : /api/organizations/gui-docs
  api-docs:
    path : /api/organizations/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

logging:
  level:
    org:
      springframework:
        web: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
